language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - rm composer.lock
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
 - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover